AWSTemplateFormatVersion: 2010-09-09

Description: Create EC2 instances.

Parameters:
  CreateInstances:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

Conditions:
  CreateInstances: !Equals [true, !Ref CreateInstances]

Resources:
  #-----------------------------------------------------------------------------
  # Roles
  #-----------------------------------------------------------------------------
  EC2BasicRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2BasicRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Pending

  #-----------------------------------------------------------------------------
  # Instance profiles
  #-----------------------------------------------------------------------------
  # For Web01 EC2 instance.
  Web01EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: EC2BasicRole
      InstanceProfileName: Web01EC2InstanceProfile

  Web02EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: EC2BasicRole
      InstanceProfileName: Web02EC2InstanceProfile

  #-----------------------------------------------------------------------------
  # Instances
  #-----------------------------------------------------------------------------
  Web01EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0218d08a1f9dac831
      InstanceType: t2.micro
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          SubnetId: !ImportValue PublicSubnet01
          # TODO: Move to private subnet
          # SubnetId: !ImportValue PrivatewSubnet01
          GroupSet:
            - !ImportValue ELBSecurityGroup
      IamInstanceProfile: !Ref Web01EC2InstanceProfile
      Tags:
        - Key: Name
          Value: Web01
        - Key: Patch Group
          Value: Web
    Condition: CreateInstances

  Web02EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0218d08a1f9dac831
      InstanceType: t2.micro
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          SubnetId: !ImportValue PublicSubnet02
          # TODO: Move to private subnet
          # SubnetId: !ImportValue PrivatewSubnet02
          GroupSet:
            - !ImportValue ELBSecurityGroup
      IamInstanceProfile: !Ref Web02EC2InstanceProfile
      Tags:
        - Key: Name
          Value: Web02
        - Key: Patch Group
          Value: Web
    Condition: CreateInstances

Outputs:
  Web01EC2Instance:
    Value: !Ref Web01EC2Instance
    Export:
      Name: Web01EC2Instance
    Condition: CreateInstances

  Web02EC2Instance:
    Value: !Ref Web02EC2Instance
    Export:
      Name: Web02EC2Instance
    Condition: CreateInstances
