---
AWSTemplateFormatVersion: 2010-09-09

Description: Create a role for Github Actions CD.

Parameters:
  CFnTemplatesRepoName:
    Type: String
    Default: codequokka/cloudformation-cicd-example

Resources:
  #-----------------------------------------------------------------------------
  # Roles
  #-----------------------------------------------------------------------------
  GithubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GithubActionsRole
      Description: Role for Github Actions to deploy CFn templates.
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidcProvider
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${CFnTemplatesRepoName}:*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      MaxSessionDuration: 3600
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Pending
          - id: W43
            reason: This role can be only used by Github actions

  #-----------------------------------------------------------------------------
  # OIDC Providers
  #-----------------------------------------------------------------------------
  GithubOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      ClientIdList:
        - sts.amazonaws.com
