---
- name:
  hosts:
    - Web01
    - Web02
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: ansible-532619504480-ap-northeast-1
    ansible_aws_ssm_region: ap-northeast-1
  tasks:
    - name: Install a httpd package
      raw: yum install -y httpd

    - name: Change DocumentRoot permission
      raw: chmod -R 777 /var/www/html/

    - name: Add index.html
      raw: echo 'Hello world' > /var/www/html/index.html

    - name: Start httpd service
      raw: systemctl start httpd.service
