plugin: aws_ec2

regions:
  - ap-northeast-1

filters:
  instance-state-name: running

# keyed_groups:
#   - key: tags.Name
#     prefix: tag_Name_
#     separator: ""

# inventory_hostnameの設定項目の優先順位
# 上から優先され、取得できなければ下に下がっていく
# この例だと Nameタグがなければ `ip-address`（パブリックIPv4アドレス）を採用し、
# それも設定されていなければプライベートIPv4アドレスを採用する
hostnames:
  - tag:Name
  - ip-address # パブリックIPv4アドレス
  - private-ip-address

compose:
  # inventory_hostnameを変更せずにansible_hostを変更する場合
  # プライベートIPv4アドレスでホストに接続したい場合
  # ansible_host: private_ip_address

  # SSM Session Managerでホストに接続したい場合は以下のようにする
  ansible_host: instance_id
