name: Check CFn templates

on:
  push:
    branches:
      - "**"
      - "!master"
    paths:
      - cfn/templates/*
      - .github/workflows/check.yml

jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install cfn-lint
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint

      # Add a matcher file to parse cfn-lint warnings.
      - name: Add problem matcher
        run: echo "::add-matcher::.github/cfn-lint.json"

      # With '-f parseable', each warnings are printed out on a sinble line.
      - name: Run cfn-lint
        run: cfn-lint ./cfn/templates/*.yml -f parseable

  cfn-nag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run cfn-nag
        uses: stelligent/cfn_nag@master
        with:
          input_path: ./cfn/templates

      # Workaround
      # GitHub Action: How to fail job if cfn-nag throws errors? #582
      # https://github.com/stelligent/cfn_nag/issues/582
      - name: Fail if cfn_nag scan contains failures, warnings
        # sum cfn_nag failures, warnigns and return it as exit code
        run: |
          exit `grep -E '^(Failures|Warnings)' cfn_nag.out | awk '{ SUM += $3} END { print SUM }'`
