name: Deploy CFn templates

on:
  pull_request:
    branches:
      - master
    paths:
      - cfn/templates/*
      - cfn/parameters/*
      - .github/workflows/deploy.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNTID }}:role/GithubActionsRole
          role-session-name: github-actios-cfn-deploy

      - name: Deploy a template for KMS
        env:
          STACK_NAME: KMSStack
          TEMPLATE_FILE: cfn/templates/kms.yml
        run: |
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file $TEMPLATE_FILE \
            --no-fail-on-empty-changeset

      - name: Deploy a template for Cloudtrail
        env:
          STACK_NAME: CloudtrailStack
          TEMPLATE_FILE: cfn/templates/cloudtrail.yml
          PARAMETERS_FILE: cfn/parameters/parameters.json
        run: |
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file $TEMPLATE_FILE \
            --parameter-overrides file://${PARAMETERS_FILE} \
            --no-fail-on-empty-changeset

      # - name: Deploy a template for Guardduty
      #   env:
      #     STACK_NAME: GuarddutyStack
      #     TEMPLATE_FILE: cfn/templates/guardduty.yml
      #     PARAMETERS_FILE: cfn/parameters/parameters.json
      #   run: |
      #     aws cloudformation deploy \
      #       --stack-name $STACK_NAME \
      #       --template-file $TEMPLATE_FILE \
      #       --parameter-overrides file://${PARAMETERS_FILE} \
      #       --no-fail-on-empty-changeset

      # - name: Deploy a template for Config
      #   env:
      #     STACK_NAME: ConfigStack
      #     TEMPLATE_FILE: cfn/templates/config.yml
      #     PARAMETERS_FILE: cfn/parameters/parameters.json
      #   run: |
      #     aws cloudformation deploy \
      #       --stack-name $STACK_NAME \
      #       --template-file $TEMPLATE_FILE \
      #       --parameter-overrides file://${PARAMETERS_FILE} \
      #       --capabilities CAPABILITY_NAMED_IAM \
      #       --no-fail-on-empty-changeset

      # - name: Deploy a template for VPC
      #   env:
      #     STACK_NAME: VPCStack
      #     TEMPLATE_FILE: cfn/templates/vpc.yml
      #     PARAMETERS_FILE: cfn/parameters/parameters.json
      #   run: |
      #     aws cloudformation deploy \
      #       --stack-name $STACK_NAME \
      #       --template-file $TEMPLATE_FILE \
      #       --parameter-overrides file://${PARAMETERS_FILE} \
      #       --no-fail-on-empty-changeset

      # - name: Deploy a template for EC2
      #   env:
      #     STACK_NAME: EC2Stack
      #     TEMPLATE_FILE: cfn/templates/ec2.yml
      #     PARAMETERS_FILE: cfn/parameters/parameters.json
      #   run: |
      #     aws cloudformation deploy \
      #       --stack-name $STACK_NAME \
      #       --template-file $TEMPLATE_FILE \
      #       --capabilities CAPABILITY_NAMED_IAM \
      #       --parameter-overrides file://${PARAMETERS_FILE} \
      #       --no-fail-on-empty-changeset

      # - name: Deploy a template for SSM Patch manager
      #   env:
      #     STACK_NAME: SSMPatchmanagerStack
      #     TEMPLATE_FILE: cfn/templates/ssm-patchmanager.yml
      #   run: |
      #     aws cloudformation deploy \
      #       --stack-name $STACK_NAME \
      #       --template-file $TEMPLATE_FILE \
      #       --no-fail-on-empty-changeset
